
version: '3.8'

services:
  
  app:
    build: .
    container_name: my_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:7
    container_name: my_redis
    ports:
      - "6379:6379"